//finding anchor markers
intersect_i_j<- data.frame(matrix(NA, nrow = 10, ncol=10))

for(i in 1:10)
{
  for(j in 1:10)
  {
    intersect_i_j[i,j]<-length(intersect(list_lg8[[i]]$marker,list_lg8[[j]]$marker))
  }
}
print(intersect_i_j)

//QTL identification
names(list_lg3)<-c("Kottapalli et al., 2008","Aryamanesh et al., 2009","Sabbavarapu et al., 2013(FW)","Sabbavarapu et al., 2013(AB)","Taran et al.,2007","Anupama et al.,","Tosh et al.,","Anuradha et al.,","Palomino et al.,2009","Winter et al.,2000","Anbessa et al.,2009","Cho et al.,2004")
library("ggplot2")
qtl_name<-qtl_study$QTL.Name[1:53]
qtl_name
r2<-qtl_study$R2[1:53]
lod<-qtl_study$LOD.SCORE[1:53]
ci<-qtl_study$CI.calculated[1:53]
trait<-qtl_study$Trait[1:53]
                       
\\   finding rmse value
install.packages("hydroGOF")
library(hydroGOF)
cons_lg2_maps<-read.csv("C:\\Users\\ishit\\OneDrive\\Documents\\Chickpea\\cons_map_lg2.csv")

chromosome<-data.frame("CaLG01","CaLG02","CaLG03","CaLG04","CaLG05","CaLG06","CaLG07","CaLG08")
gene<-"GTGGCGCGGGCGTCAAGCGCGACTGATCGTATGACGGACACGATCTTCGCCCTGGCGACGGCGGCCGGCC
GCTCGGCCGTTGCGGTGGTGCGCGTATCCGGTCCCCGGTCGTCGGAGATCGCCGCTGCGCTTTGCGGTCG
CCTGCCATCGCCCCGCTTGGCGTCGGTCCGGACGCTGAAGCACAATGGGGTGGCCTTGGACGCGGCGCTG
GTCCTGCGCTTCGAAAAGCCGGCCAGTTATACCGGCGAAGACAGTGTCGAGTTTCACGTGCACGGCGGCC
GCGCCGTGGTCGAGGCCTTGCTTGCGGCGCTGTCGGAACTTGGGGCTCGCCTGGCCGAGGCGGGCGAGTT
CACGCGGCGGGCGTTCGAGAACGGCAAGCTTGATCTCGCCCAGGCCGAGGGCGTGGCCGACCTGATCGAC
GCCGAGACCGAGGCTCAGAGGCGTCAGGCCCTGGGCCAGGTGGGCGGCGCCTTGAGCCAGCGCTACGACC
GCTGGCGTGATCTGCTGGTCCAGGCCTTGGCCATGCTGGAGGCGGCCGTCGACTTTCCTGATGAGGATCT
GCCCGAGGAAGTGGCCGAGCGCGCCCGTCCTGGACTGCGCCAACTCAGCGCCGAACTGAACGCGGCGCTG
GCGGACGTTTCACGGGGGCGGCGGGTGCGAGACGGCTTCCGCATTGCGCTCATTGGTGCGCCAAACGCCG
GGAAGAGCACCTTACTCAATGGCCTCGCCGAGCGGGACGCGGCGATCGTGACCGATGTGGCCGGGACCAC
ACGTGACGTGATTGAGGTCCCCCTGGTGCTGGGCGGCTACAAGGTGTTGGTCGCGGATACGGCCGGGATA
CGCGAGACTGCGGATGTGATCGAGGCCGAGGGTGTTCGTCGCGCCAAGGCGTGGGCCGAAGCGGCGGATC
TTCGTCTTTGGGTCGTCGATGGTTTTCACGTGAAACAAGCCGACGCGCGGCCTGAAGCGATCCGCGTTGG
CGACTGGCTGATCCTCAACAAGACGGATATCGCCGATGCGGACGCCTCGGCGCATGTGGCGGAGCGCTGG
GCGGGGGAGGGGCTTACTGTTCTGCATATTGCGGGGACGTCTGCTGAGGGTCCCGAGGCCCTCCGCGCCG
CGCTCGCGTCTCACGTGGCGGACGCTTTGTCGGGCGCGGAGTTCCCGGCCGCTACCCGTCTGAGACATGC
CGAGCGCCTGTCAGAGGCGCGGTCCTATCTGGAACGCGCGCTGTCGGATGTCGGGCTGGAGGTGGAGTTG
GCCGCTGAAGATGTGCGGCTGGCGGCCCGGGCCCTGGAGCGCATCTCCGGCCGTATCGATCCTGAGGACG
TTCTTGGACGGGTCTTTTCGACCTTCTGTATCGGCAAGTGA"
trna<-gsub("T","U",gene)
trna
